name: frontend-ci

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 🧰 Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install pnpm
        run: |
          npm install -g pnpm
          echo "PNPM PATH: $(which pnpm)"
          pnpm --version

      - name: 📥 Install dependencies
        run: pnpm install

      - name: 🛠 Run build
        run: pnpm build
