name: frontend-ci

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISABLE_ESLINT_PLUGIN: true

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "21.2.0"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Try build
        run: pnpm run build
