name: frontend-ci

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "21.2.0"
          cache: "pnpm"

      - name: Install pnpm
        run: |
          npm install -g pnpm
          echo "PNPM PATH: $(which pnpm)"
          pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Try build
        run: pnpm run build
